# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "funtimes"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Len Smith"]
  s.date = "2011-10-05"
  s.description = "Manage date ranges, months and quarters"
  s.email = "ignu.smith@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "funtimes.gemspec",
    "lib/funtimes.rb",
    "lib/funtimes/date_range.rb",
    "lib/funtimes/month.rb",
    "lib/funtimes/quarter.rb",
    "lib/funtimes/week.rb",
    "spec/date_range_spec.rb",
    "spec/month_spec.rb",
    "spec/quarter_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/week_spec.rb"
  ]
  s.homepage = "http://github.com/ignu/fun-times"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Manage date ranges, months and quarters"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
  end
end

